version: "3.9"
services:

  service1:
    build:
      context: ./service1
    environment:
      SERVICE2_URL: http://service2:3100
    depends_on:
      - service2
    ports:
      - '3000:3000'

  service2:
    build:
      context: ./service2
    ports:
      - '3100:3100'
