version: "3.9"
services:

  publisher-app:
    build:
      context: ./publisher
    environment:
      HTTPS_ENABLED: "true"
      SUBSCRIBER_FQDN: "publisher:3000"
    depends_on:
      - subscriber-app
    ports:
      - '3000:3000'

  subscriber-app:
    build:
      context: ./subscriber
    environment:
      HTTPS_ENABLED: "true"
    ports:
      - '3100:3100'
