version: "3.9"
services:

  publisher-app:
    build:
      context: ./publisher
    environment:
      HTTPS_ENABLED: "false"
      SUBSCRIBER_FQDN: "publisher-app:3000"
      SUBSCRIBER_DAPR: "publisher-dapr:3601"
    depends_on:
      - subscriber-dapr
    ports:
      - '3000:3000'
    networks:
      - default

  subscriber-app:
    build:
      context: ./subscriber
    environment:
      HTTPS_ENABLED: "false"
    ports:
      - '3100:3100'
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default
    logging:
      driver: none

  subscriber-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "--app-id",
        "subscriber-dapr",
        "--app-port",
        "3100",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--components-path",
        "./components"
      ]
    volumes:
      - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --components-path argument.
    depends_on:
      - subscriber-app
      - rabbitmq
    network_mode: "service:subscriber-app"
    networks:
      - default

  publisher-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "--app-id",
        "publisher-dapr",
        "--dapr-http-port",
        "3601"
      ]
    depends_on:
      - subscriber-dapr
    network_mode: "service:subscriber-dapr"
    networks:
      - default

  placement:
    image: "daprio/dapr"
    command: [ "./placement", "--port", "50006" ]
    ports:
      - "50006:50006"

networks:
  default:
    driver: bridge
